apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "appd-infrastructure.name" . }}
    chart: {{ template "appd-infrastructure.chart" . }}
    release: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ .Chart.Description }}
    release: {{ .Chart.Version }}
