apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: romoss-calisti-panoptica01
  region: ap-southeast-2

nodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 2
    volumeSize: 60
