# Dockerfile to create the Blue image
# Repalce the styles.css file with one that has set the text colour to dark Blue

FROM gcr.io/google-samples/microservices-demo/frontend:v0.3.6

ADD ../styles-blue.css /src/static/styles/styles.css
