# Dockerfile to create the Green image
# Repalce the styles.css file with one that has set the text colour to dark Green

FROM gcr.io/google-samples/microservices-demo/frontend:v0.3.6

ADD styles-green.css /src/static/styles/styles.css

EXPOSE 8080/tcp

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV GOTRACEBACK=single

ENTRYPOINT "/src/server"
