# Dockerfile to create the Blue image with frontend:v0.3.6 version
# Repalce the styles.css file with one that has set the text colour to dark Blue

FROM gcr.io/google-samples/microservices-demo/frontend:v0.3.6

ADD styles-blue.css /src/static/styles/styles.css

EXPOSE 8080/tcp

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV GOTRACEBACK=single

ENTRYPOINT "/src/server"
