apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: smm-custom-meshgateway
  name: smm-custom-meshgateway
---
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  name: custom-gw
  namespace: smm-custom-meshgateway
spec:
  istioControlPlane:
    name: cp-v111x
    namespace: istio-system
  runAsRoot: true
  service:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
      - name: http-onlinebotique
        port: 81
        protocol: TCP
        targetPort: 8081
      - name: http-teastore
        port: 82
        protocol: TCP
        targetPort: 8082
      - name: https
        port: 443
        protocol: TCP
        targetPort: 8443
    type: LoadBalancer
  type: ingress
